apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - host: guestbook.info
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80                  