# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.master.serviceName}}
  labels:
{{- include "labels.redis-master" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.master.containers.port}}
    targetPort: {{ .Values.master.containers.port}}
  selector:
{{- include "labels.redis-master" . | nindent 4 }}